apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-mongo-sts
  namespace: default
spec:
  serviceName: orders-mongo-srv
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongodb
  template:
    metadata:
      labels:
        app: orders-mongodb
    spec:
      containers:
        - name: orders-mongodb
          image: mongo:8.0
          command:
          - mongod
          - --replSet
          - rs0
          - --bind_ip_all
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
      namespace: microservices
    spec:
      storageClassName: standard
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 300Mi

---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-srv
spec:
  selector:
    app: orders-mongodb
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017