apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tickets-mongodb-sts
spec:
  serviceName: tickets-mongo-srv
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongodb
  template:
    metadata:
      labels:
        app: tickets-mongodb
    spec:
      containers:
        - name: tickets-mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-tickets-pvc
              mountPath: /data/db
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
  volumeClaimTemplates:
  - metadata:
      name: mongo-tickets-pvc
      namespace: microservices
    spec:
      storageClassName: standard
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 300Mi

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  selector:
    app: tickets-mongodb
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017