apiVersion: batch/v1
kind: Job
metadata:
  name: orders-mongo-init
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mongo-init
        image: mongo:8.0
        command:
        - mongosh
        - --host
        - orders-mongo-sts-0.orders-mongo-srv
        - --eval
        - 'rs.initiate({"_id": "rs0", "members": [
            {"_id": 0, "host": "orders-mongo-sts-0.orders-mongo-srv:27017"},
          ]})'