apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  MONGO_URI: mongodb://auth-mongo-srv:27017/auth
  CLIENT_URL: http://local.test.com:3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: microservices:auth
          imagePullPolicy: IfNotPresent
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: project-secrets
                  key: jwt-key
          envFrom:
            - configMapRef:
                name: auth-config
              
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - name: auth
      port: 5000
      protocol: TCP

