apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: microservices:orders
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: project-secrets
                  key: jwt-key
            - name: MONGO_URI
              value: mongodb://orders-mongo-srv:27017/orders
            - name: ORDER_EXPIRATION
              value: '60'
            - name: NATS_URL
              value: http://nats-srv:4222
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  type: ClusterIP
  ports:
    - name: orders
      port: 5002
      protocol: TCP

